spring:
  application:
    name: ScoreMate

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scoremate?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: scoremate
    password: kty4869!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: change-this-to-a-random-secret-string-at-least-32-bytes-long
  expiration-ms: 3600000

logging:
  level:
    ScoreMate.ScoreMate: debug
